name: stochastic_music

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - pip

  - pip:
      - streamlit
      - plotly
      - mido
      - pretty_midi
      - pyyaml
      - networkx
      - moviepy
      - imageio-ffmpeg